### ISSUE TITLE
Remove the project secrets from git

### ISSUE THREAD

**Issue by TarekkMA** [m7m9d-a7medy/esp32-gas-sensor-iot#1]
Keep the secret file of this project out of git.

you can follow these guides:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository

https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history

**Comment by m7m9d-a7medy** [comment]
Thanks dude

**Comment by m7m9d-a7medy** [comment]
Hide sensitive data feature
